//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytics
    {
        public long Analytics_id { get; set; }
        public System.DateTime Analytics_date { get; set; }
        public long Sites_id { get; set; }
        public int Analytics_value { get; set; }
    
        public virtual Sites Sites { get; set; }
    }
}
