//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.UserProjectsM2M = new HashSet<UserProjectsM2M>();
        }
    
        public long Project_id { get; set; }
        public string Project_name { get; set; }
        public string Project_comment { get; set; }
        public bool Project_open { get; set; }
    
        public virtual ICollection<UserProjectsM2M> UserProjectsM2M { get; set; }
    }
}
