//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiseWorkEntities : DbContext
    {
        public RiseWorkEntities()
            : base("name=RiseWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Analytics> Analytics { get; set; }
        public DbSet<Projects> Projects { get; set; }
        public DbSet<Sites> Sites { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserProjectsM2M> UserProjectsM2M { get; set; }
    }
}
