//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProjectsM2M
    {
        public long UserProjectsM2M_id { get; set; }
        public Nullable<System.DateTime> UserProjectsM2M_date { get; set; }
        public Nullable<long> UserProjectsM2M_hours { get; set; }
        public Nullable<long> User_id { get; set; }
        public Nullable<long> Projects_id { get; set; }
        public string UserProjectsM2M_comment { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual User User { get; set; }
    }
}
