//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserProjectsM2M = new HashSet<UserProjectsM2M>();
        }
    
        public long User_id { get; set; }
        public string User_name { get; set; }
    
        public virtual ICollection<UserProjectsM2M> UserProjectsM2M { get; set; }

		public string User_password { get; set; }
	}
}
